### ISSUE TITLE
Put the "joke" and "punch" element in a variable for improving the performance.

### ISSUE THREAD

**Issue by rahuldahal-zz** [LaxmanJonchhen12/Random-Joke-Generator#1]
## The problem

Every time the `getRandomJoke` function gets invoked, the JS engine has to perform a *lookup* on the DOM.
Since, [that](https://github.com/LaxmanJonchhen12/Random-Joke-Generator/blob/cbd07394cd41da6223dec323c7c902c1c7d5410c/js/main.js#L2) function gets invoked on every [click](https://github.com/LaxmanJonchhen12/Random-Joke-Generator/blob/cbd07394cd41da6223dec323c7c902c1c7d5410c/js/main.js#L16) of the button, the JS engine performs *lookup*on  every single click.

## Suggested fix

1.  Grab the element(s) once, and store them in the memory.
``` js
let jokeElement = document.getElementById("joke");
let punchLineElement = document.getElementById("punchine");
```

2. Reference them inside the function

```js
function getRandomJoke(){
    // do the fetching...
    // jokeElement.innerHTML = valueFromFetch
    // punchLineElement.innerHTML = valueFromFetch   
}
```

**Comment by LaxmanJonchhen12** [comment]
Thanks for the suggestion rahul. Nice tip for performance optimization. Will work on it

**Comment by LaxmanJonchhen12** [comment]
Thank you rahul the issue has been solved by implementing the suggestion by you
